/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IComplianceBridge,
  IComplianceBridgeInterface,
} from "../../../contracts/interfaces/IComplianceBridge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "originChain",
        type: "string",
      },
      {
        internalType: "uint32",
        name: "verificationType",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "issuanceTimestamp",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "expirationTimestamp",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "proofData",
        type: "bytes",
      },
      {
        internalType: "string",
        name: "schema",
        type: "string",
      },
      {
        internalType: "string",
        name: "issuerVerificationId",
        type: "string",
      },
      {
        internalType: "uint32",
        name: "version",
        type: "uint32",
      },
    ],
    name: "addVerificationDetails",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "issuerAddress",
        type: "address",
      },
    ],
    name: "getVerificationData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "verificationType",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "expirationTimestamp",
        type: "uint32",
      },
      {
        internalType: "address[]",
        name: "allowedIssuers",
        type: "address[]",
      },
    ],
    name: "hasVerification",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IComplianceBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IComplianceBridgeInterface {
    return new Interface(_abi) as IComplianceBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IComplianceBridge {
    return new Contract(address, _abi, runner) as unknown as IComplianceBridge;
  }
}
