/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IComplianceBridge__factory } from "./IComplianceBridge__factory";
export { ISWTRProxy__factory } from "./ISWTRProxy__factory";
