/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ITransparentUpgradeableProxy } from "./ITransparentUpgradeableProxy";
export type { ProxyAdmin } from "./ProxyAdmin";
export type { SWTRImplementation } from "./SWTRImplementation";
export type { SWTRProxy } from "./SWTRProxy";
export type { TransparentUpgradeableProxy } from "./TransparentUpgradeableProxy";
