/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IComplianceBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addVerificationDetails"
      | "getVerificationData"
      | "hasVerification"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addVerificationDetails",
    values: [
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerificationData",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVerification",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addVerificationDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerificationData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVerification",
    data: BytesLike
  ): Result;
}

export interface IComplianceBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IComplianceBridge;
  waitForDeployment(): Promise<this>;

  interface: IComplianceBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addVerificationDetails: TypedContractMethod<
    [
      userAddress: AddressLike,
      originChain: string,
      verificationType: BigNumberish,
      issuanceTimestamp: BigNumberish,
      expirationTimestamp: BigNumberish,
      proofData: BytesLike,
      schema: string,
      issuerVerificationId: string,
      version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getVerificationData: TypedContractMethod<
    [userAddress: AddressLike, issuerAddress: AddressLike],
    [string],
    "nonpayable"
  >;

  hasVerification: TypedContractMethod<
    [
      userAddress: AddressLike,
      verificationType: BigNumberish,
      expirationTimestamp: BigNumberish,
      allowedIssuers: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addVerificationDetails"
  ): TypedContractMethod<
    [
      userAddress: AddressLike,
      originChain: string,
      verificationType: BigNumberish,
      issuanceTimestamp: BigNumberish,
      expirationTimestamp: BigNumberish,
      proofData: BytesLike,
      schema: string,
      issuerVerificationId: string,
      version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getVerificationData"
  ): TypedContractMethod<
    [userAddress: AddressLike, issuerAddress: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasVerification"
  ): TypedContractMethod<
    [
      userAddress: AddressLike,
      verificationType: BigNumberish,
      expirationTimestamp: BigNumberish,
      allowedIssuers: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
