/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IComplianceBridge } from "./IComplianceBridge";
export type { ISWTRProxy } from "./ISWTRProxy";
